### ISSUE TITLE
Browser Back Button with Debug Panel Open

### ISSUE THREAD

**Issue by arietrouw** [XYOracleNetwork/os#1]
**Describe the bug**
With the debug panel open, clicking on the back button next tot he browser url navigates away from the xyOS.  When doing this with a dApp open, it closes the dApp.

**To Reproduce**
1. Launch xyOS
2. Click on the Bug Icon at the upper right
3. Click the browser's back button
4. Notice navigate away from xyOS

**Expected behavior**
Expected the Debug panel to close and to not navigate away

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 2.1.0 Build 8652b86

**Additional context**
None

**Comment by jonesmac** [comment]
~~Got a solution for this and should make it into the next release.~~

Close but still needs some work.
