### ISSUE TITLE
Debug Screen

### ISSUE THREAD

**Issue by Sc2KiiiA** [XYOracleNetwork/os#10]
**Describe the bug**

**To Reproduce**
1. Go to 'debug' the bug next to nite/day
2. Click on 'details'
3. Scroll down to 'the right'
4. You Can See the error showing the data in the wrong <td>(bracket) should be centered and it's on a (right nav bar)

**Expected behavior**

**Screenshots**
![Screenshot_20240501_221200_Chrome.png](https://github.com/XYOracleNetwork/os/assets/25086107/eba789b4-09c1-43b2-a3f6-b4f83a521e54)

**Smartphone (please complete the following information):**
 - Device: [ Samaung S21+5G ]
 - OS: [ Android 14 ]
 - Browser [ Chrome ]
 - Version [ 124.0.6367.82]

**Additional context**
I assume there is one to many line breaks in the code or such actions as it's sending the main content to the right nav bar.

**Comment by arietrouw** [comment]
Confirmed.

**Comment by arietrouw** [comment]
Debug screen is a work in progress.  e have removed the ability to click on details for items for now.
