### ISSUE TITLE
After importing SeedPhrase "! MARK" on HOME Node Screen

### ISSUE THREAD

**Issue by MetaTireMan** [XYOracleNetwork/os#12]
Please see attached screenshot...

![image](https://github.com/XYOracleNetwork/os/assets/167895958/bab0f14b-c8b8-4e7c-a1e4-55b72c37c9c0)

After importing my SeedPhrase, the RED EXCLAIMATION mark continues to show?...

As a User, after importing a saved SeedPhrase, I would think the "!" would disappear.

Just my thinking.

**Comment by jonesmac** [comment]
thanks @MetaTireMan.  Should be fixed in the next release.
