### ISSUE TITLE
Error Message when a Profile Connection can not be made

### ISSUE THREAD

**Issue by arietrouw** [XYOracleNetwork/os#14]
**Describe the bug**
When trying to connect to a node that is not currently on-line, I get a weird error.

**To Reproduce**
1. Go to xyOS > Profile > Discover
2. Paste a remote node to discover that you know is not currently on into field
3. Click Discover and wait for error
4. Dead Module Error occurs (which is valid) but not user friendly

**Expected behavior**
Better user message and probably the option to keep trying

**Screenshots**
<img width="794" alt="image" src="https://github.com/XYOracleNetwork/os/assets/6313781/1d6a659d-31cd-4f9d-86b3-1f0fd008f7eb">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: XYO | OS (xyOS) v2.1.0 (Beta) [2faa1ae] 

**Smartphone (please complete the following information):**
 N/A

**Additional context**
None

**Comment by jonesmac** [comment]
closing as its a dup of https://github.com/XYOracleNetwork/os/issues/11
