### ISSUE TITLE
HEALTH dapp / CSS adjustment

### ISSUE THREAD

**Issue by MetaTireMan** [XYOracleNetwork/os#15]
Please see the attached screenshot...

![image](https://github.com/XYOracleNetwork/os/assets/167895958/84e2d63a-1c87-4e34-ae05-ed51363b4d2f)

The TIMESTAMP column frontend/CSS needs adjustment, it is being partially cutoff.

**Comment by MetaTireMan** [comment]
Interesting I think I found the issue...

Has to do with whether you are CLOSING vs MINIMIZING the dapps within the NODE.

See attached screenshot, when all dapps are CLOSED and then you open HEALTH...

![image](https://github.com/XYOracleNetwork/os/assets/167895958/dea745cb-b315-4054-a16d-5cf03d1cee20)

It's better, however a (,) is being added after the date. Looks like there could be some padding which can be added to the right of TIMESTAMP too.

**Comment by MetaTireMan** [comment]
I think the issue is we are squeezing TIMESTAMP into this area/field instead of just using DATE?

![image](https://github.com/XYOracleNetwork/os/assets/167895958/debff8d1-0234-4d09-aa0b-70c77b739dde)

**Comment by jordantrouw** [comment]
Will be addressed in next patch.
