### ISSUE TITLE
Removing Friends/Saved Profiles

### ISSUE THREAD

**Issue by Sc2KiiiA** [XYOracleNetwork/os#17]
**Describe the bug**
 The Pop-up window when removing a user from the profile does not automatically close after clicking Remove.

**To Reproduce**

1. Go to 'profile'
2. Click on 'remove'
3. The user gets removed, but the pop-up stays open after clicking remove.

**Expected behavior**
Normally, when clicking the button(remove), the pop-up would close as this is starting and ending the script.

**Screenshots**

I've seen this on both Android and Linux, both using Chrome.

**Additional context**
On a side note, maybe show "who" has connected to you via the profile tab 😉 
Maybe leave a signature (when online a box shows). Maybe this can be qued and fetched for a later date. 

Example: My node is online 24/7 it would be cool to see who has connected to me, maybe when I was a sleep or at work.
829f0d054afc835a0d06a519d3046ed4807bf2e6 would be the address in question.

**Comment by jonesmac** [comment]
@jordantrouw I believe I fixed this one!
