### ISSUE TITLE
xNS Suggestion

### ISSUE THREAD

**Issue by Sc2KiiiA** [XYOracleNetwork/os#18]
**Is your feature request related to a problem? Please describe.**
Not really. 

**Describe the solution you'd like**
The amount of text capped inside of the xNS registry.

**Describe alternatives you've considered**
Currently keys are 40 digits, maybe the xNS should be limited to 40 digits as to many could cause a break in the code.

**Additional context**
When searching, a name should not be longer than the key of a user 40 is pretty big
Icanwrightasentencewithfourtydigits.XYO
( I can write a sentence with fourty digits. XYO)
 And that's not even 40, as this image was 56 long, haha![Screenshot_20240503_181618_Chrome.png](https://github.com/XYOracleNetwork/os/assets/25086107/937b059e-894e-45fd-b4c4-9f775a39c56d)

**Comment by jonesmac** [comment]
Thanks for catching this.  I think we will wrap the long names to adapt to really small screen sizes.

<img width="355" alt="image" src="https://github.com/XYOracleNetwork/os/assets/885417/91a21be1-2aca-4f85-83ff-4ecfc7237bb4">
