### ISSUE TITLE
No ability to GO BACK / CHANGE / EDIT xNS

### ISSUE THREAD

**Issue by MetaTireMan** [XYOracleNetwork/os#19]
See attached screenshots...

![image](https://github.com/XYOracleNetwork/os/assets/167895958/fb1ae9c9-7c90-4fee-bf03-ccecb3c1f490)

![image](https://github.com/XYOracleNetwork/os/assets/167895958/df4f0973-d56a-41d7-9930-605b0b0389eb)

After selecting xNS, it brings you to the CHECKOUT; with no way to GO BACK to change/edit your name.

Only way to workaround was to Hit BUY NAME, you can enter another xNS name then brings you back to CHECKOUT with other xNS searched.

This may be working as intended...However User Experience could be better...I had to self discover this, which many Users will just give up.

Instead maybe an option TO ADD additional xNS before automatically sending the User to CHECKOUT.

Would be good if a ShoppingCart style was implemented so the User stays on the BUY NAMES screen until they select all xNS they want to purchase.

Additional Note:
CHECKOUT page gets buggy with multiple xNS...ability to scroll up and down on iPhone does not work.

**Comment by arietrouw** [comment]
Hitting the Delete button (which maybe should be more obviously a button) removes an xns name from the cart.  Editing them does not make sense since they will have to re-check availability anyway.  I do agree that this flow can be better, and we will also look into the iOS issue.

**Comment by jordantrouw** [comment]
Can't replicate the scroll in the additional note

**Comment by jordantrouw** [comment]
Working on this now — updated UI for longer names on randomizer card, addressed scroll issue noted above.
