### ISSUE TITLE
XNS Estimate Error Message is Lacking

### ISSUE THREAD

**Issue by arietrouw** [XYOracleNetwork/os#2]
**Describe the bug**
When Checking Availability of a name, if it is not available, the error shown is not very helpful.

**To Reproduce**
1. Go to xyOS > Name Service > Buy Names
2. Type in 'xyo' into the name field
3. Click Check Availability
4. Error says 'Error: DomainLease Payload not found'

**Expected behavior**
I expected the error to say that the name xyo.xyo is either already taken or not allowed to be bought because it is reserved.

**Screenshots**
<img width="361" alt="image" src="https://github.com/XYOracleNetwork/os/assets/6313781/fe179643-988f-4201-beaa-fd824f1c75b6">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: xyOS 2.1.0 Build F70399c

**Smartphone (please complete the following information):**
N/A

**Additional context**
Message also should probably not be an 'oops...' message

**Comment by jonesmac** [comment]
Error Messages will be thrown and aggregated

**Comment by jonesmac** [comment]
@arietrouw have a branch that successfully consumes the error messages.  It looks like there's an error with the error 🥁 
![image.png](https://zube.io/files/xyo/0c95b0bb1a22f903b0e65d6ce014b81c-image.png)
