### ISSUE TITLE
"ExposedNode" message instead of Name or Node address

### ISSUE THREAD

**Issue by jebscc** [XYOracleNetwork/os#20]
**Describe the bug**
When queried an already connected node, you will receive a message saying "Error: Module with name ExposedNode already added". Which is a valid statement as the node is already connected, but I would expect the Name or Node address to appear instead of "ExposedNode".

**To Reproduce**
1. Launch Profile dApp.
2. Click on Discover.
3. Enter in a "new" valid node address and save it to your list.
4. Attempt to readd node which is when message will appear.

**Expected behavior**
Display node address or name (if available), instead of displaying "ExposedNode".

**Screenshots**
![image](https://github.com/XYOracleNetwork/os/assets/19239389/077e1f82-61fb-4c9f-a9c1-5535edb1f3e4)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 124.0.6367.119

**Comment by jonesmac** [comment]
Believe this was solved by not using names from configs when mounting found modules from pub sub bridge

**Comment by jebscc** [comment]
Tried a couple of different methods to replicate this issue which is as follows:

1. I queried 829f0d054afc835a0d06a519d3046ed4807bf2e6 - LewSalesLinux and received the following result.

    Result: No longer seeing this issue with this method.
    ![image](https://github.com/XYOracleNetwork/os/assets/19239389/d9373842-1290-4693-9592-e1a7fcb71924)

2.  I queried 76f37c376c175ef1c38ad33e09e7b5976fdb058f -JimTheAdventurer. Yes, I know, I queried myself but this time I was able to replicate the issue.

    Result: Issue replicated...
    ![image](https://github.com/XYOracleNetwork/os/assets/19239389/8dd5c04a-d20f-44b4-8995-1fa0308a3fc8)
