### ISSUE TITLE
DAILY PAYLOAD...Not showing proper in iPhone 15.

### ISSUE THREAD

**Issue by MetaTireMan** [XYOracleNetwork/os#21]
See attached screenshot...

![image](https://github.com/XYOracleNetwork/os/assets/167895958/a0f529a6-baf3-42e7-b2f1-75260a512c3a)

Responsive Mobile view is not responding properly...it is chopping of the "C" and "G" in Coming Soon.

**Comment by jebscc** [comment]
Seeing same issue on iPhone 12.

![IMG_0231](https://github.com/XYOracleNetwork/os/assets/19239389/ed5a71bd-95d7-4f98-bbb2-6d2efdd72cae)

**Comment by jordantrouw** [comment]
Will be addressed in next patch.
