### ISSUE TITLE
Profile Bio would not save correctly

### ISSUE THREAD

**Issue by EricaBeall** [XYOracleNetwork/os#22]
**Describe the bug**
Profile Bio About Me dialog box does not seem to save correctly, even after editing and re-saving.

**To Reproduce**
1. Access My Profile dapp
2. Click on Edit
3. In about me box, start typing away.
4. Save, but then click edit again, correct something, re-save

**Expected behavior**
Well try to make this simple to explain, I typed a little bio in the About Me box and saved it. Initially I didn't see the X(Twitter) box, for your X account below, so I pasted my X address/Link in the About Me profile and saved. I noticed I had missed 2 letters in 2 words in my bio, so I hit edit again, made corrections, but after hitting save, only 1 correction stayed, the other reverted back and half my X address was gone. (Yeah, I didn't really need it because it's below, but at the time I still didn't see that, so that's moot) So I repeated same steps and corrections, my address stayed in full but again the letter disappeared. So again repeated steps, hitting edit, corrected missing letter, hit save but then X address half disappeared again. This process went on 2 more times, before it finally saved with out removing either or both corrections. Screenshot shows completed Profile, I got one screenshot with an "a" missing in the word and before XY Labs. In fact I just removed that word all together cause I couldn't get an "a" to stay

![Screenshot_20240509_024826_Chrome](https://github.com/XYOracleNetwork/os/assets/114159939/200db5b9-1e64-4988-9611-8b308ca8ca80)

![Screenshot_20240509_024943_Chrome](https://github.com/XYOracleNetwork/os/assets/114159939/ce67e864-b58d-44a6-8812-a11af06d7e15)

**Smartphone (please complete the following information):**
 - Device: Samsung A14
 - OS: One UI 6.0 Android 14
 - Browser: Chrome
 - Version: Chrome 124.0.6367.114

**Additional context**

**Comment by arietrouw** [comment]
I believe that this is due to us not supporting the links.  Maybe we should consider allowing the bio to be markdown?

**Comment by EricaBeall** [comment]
Cant say Im very familar w Markdown, but bestvof my knowledge that would do the trick. Everyone who uses Markdown says its the best thing since sliced bread. Awesome.

**Comment by arietrouw** [comment]
Still an issue?

**Comment by jonesmac** [comment]
I was able to reproduce the issue locally.  I believe it's because saving a previously saved version of any of the profile fields means the archivist doesn't add a new payload.  When a save occurs, the latest payload is not the one we expect but rather the previous version.  I think we can safely solve this by clearing the memory archivist on each field before saving the updated value.

**Comment by jonesmac** [comment]
@EricaBeall thanks for the detailed steps.  I believe this is fixed and will go out with the next release!

**Comment by EricaBeall** [comment]
Sorry for late response...(Ive briefly mentioned at various times in
various communications, I had a really tough nearly 2 yrs, wrongfully
terminated from work, lawsuit, homelessness, etc...Its finally but slowly
turning around for me...Back to work, school, no longer homeless but it
still demands so much of my time...putting my life back together)
anyway...Thank You, Im way overdue to continue exploring the OS, but as fog
lifts, Ill get back on it. See if anything crops up or problem re-occurs.
Very impressed you continued to work on issue, and rather minor in many
ways.
Heard some big profitable news is coming XYO, so standing by, awaiting
such. We all will benefit from such. Thanks again. Keep at it!
