### ISSUE TITLE
Overlapping Cards in My XNS Names

### ISSUE THREAD

**Issue by jordantrouw** [XYOracleNetwork/os#23]
**Describe the bug**
Card with XNS Name overlapping card behind it

**To Reproduce**
1. Go to https://node.xyo.network/name-service/my-names
2. Own XNS Names
3. See picture of issue

**Screenshots**
<img width="1493" alt="Screenshot 2024-05-13 at 8 07 10 AM" src="https://github.com/XYOracleNetwork/os/assets/37600451/2d3bfe54-1174-4e80-8eb2-d7d360705171">

**Desktop (please complete the following information):**
 - OS: MACOS
 - Browser CHROME

**Comment by Sc2KiiiA** [comment]
Currently, this is what it looks like on Android.

![Screenshot_20240511_083730_Chrome.png](https://github.com/XYOracleNetwork/os/assets/25086107/5d728c41-b9de-43dd-9bf4-d7169505c9b9)

**Comment by arietrouw** [comment]
Fixed
