### ISSUE TITLE
UnSure

### ISSUE THREAD

**Issue by Sc2KiiiA** [XYOracleNetwork/os#24]
**Describe the bug**
Clicked on Profile,

**To Reproduce**
Everything was fine. I Clicked on profile and ...

**Expected behavior**
I don't know what to expect,but I know that I'm not expecting an error box 😅

**Screenshots**
..!![Screenshot_20240511_081755_Chrome.png](https://github.com/XYOracleNetwork/os/assets/25086107/8cc18746-57d7-403d-8fc3-4b43f5c8380d)

**Smartphone (please complete the following information):**
 - Device: [SamSung A21+5G]
 - OS: [e.g. Android14 ]
 - Browser [Chrome ]
 - Version [too lazy to look, but same as before]

**Additional context**
#StrongerTogether

**Comment by Pkersfan88** [comment]
You find an error box

**Comment by arietrouw** [comment]
Can not reproduce
