### ISSUE TITLE
 Share Option.

### ISSUE THREAD

**Issue by Sc2KiiiA** [XYOracleNetwork/os#30]
**Describe the bug**
Share Option only takes you to http://node.xyo.network/profile (no real share option)

**To Reproduce**
1. Simply try to share, 
2. Takes you to a page that would look cool to share. But one has to take a screenshot and post the node link 

**Expected behavior**
Normally, when sharing, it gives you a link to share.

**Screenshots**
![Screenshot_20240813_211827_Chrome.png](https://github.com/user-attachments/assets/63d46805-6d0f-40e1-a405-1cb75fcff520)

**Smartphone (please complete the following information):**
 - Device: [e.g. android 
 - OS: [e.g. amdroid 14]
 - Browser [headless browser/ "app"]

**Additional context**

I'm pretty sure it's just not completed yet.

**Comment by Sc2KiiiA** [comment]
Found it ...
I guess when I saw the gear, I assumed it was to edit the image and such details.

Maybe the share button should be on the previous page.

![Screenshot_20240813_221137_Chrome.png](https://github.com/user-attachments/assets/326df765-10a3-4cd8-bbd9-d94a0bec356b)

![Screenshot_20240813_220158_Chrome.png](https://github.com/user-attachments/assets/099e6786-f9d4-42d1-9425-42cf016e7c17)

**Comment by JoelBCarter** [comment]
Excellent find @Sc2KiiiA 👏🏼 👏🏼 👏🏼 .  We're talking about how to make this more clear right now.  Thanks for this feedback.  You rock 🎸 .

**Comment by jordantrouw** [comment]
Fix will be live on next update.
