### ISSUE TITLE
Profile discovery is broke. (Adds 0x)

### ISSUE THREAD

**Issue by Sc2KiiiA** [XYOracleNetwork/os#31]
**Describe the bug**
One can't search via a name.

**To Reproduce**
1. Go to 'Profile'
2. Click on 'discovery'
3. Type 'lewsales.xyo' in the searchbox
4. See error as ( 0xlewsales.xyo )

**Expected behavior**
A Link to my Profile 😆🤣.

**Screenshots**

![Screenshot_20240813_214507_Chrome.png](https://github.com/user-attachments/assets/b31627b7-f4de-4449-89ee-0a115c9bf45c)

**Smartphone (please complete the following information):**
 - Device: [ Android s21 +5G ]
 - OS: [ Android 14 ]
 - Browser [ Chrome ]

**Additional context**
Simple fix, none the less.

**Comment by jonesmac** [comment]
@Sc2KiiiA I wasn't able to reproduce the exact bug you had.  That being said, it looks like from the error you were trying to search for `0xlewsales.xyo`.  Just wanted to confirm that you intended to add the 0x when you searched and you expected to resolve that name specifically?

**Comment by Sc2KiiiA** [comment]
Here is a video ... as ive tried this about 20 times

https://github.com/user-attachments/assets/3b3ea2e4-9b5a-46fb-a710-9c4ce56e07de

https://cdn.discordapp.com/attachments/786826615802822656/1273342473552400454/Screen_Recording_20240814_120614_Chrome.mp4?ex=66be4417&is=66bcf297&hm=6975059856cae624649a2b0dbfa6c1a54ddfb2f0a8a1b072631755807d7aeca0&

**Comment by jonesmac** [comment]
Thanks @Sc2KiiiA.  Very helpful.  Would you mind doing one more favor and sending me a screenshot of the current version of the OS you are running?  you can find it at https://node.xyo.network/about

**Comment by jonesmac** [comment]
also, can you post the chrome version as well?

Should be in the settings - https://www.androidauthority.com/check-google-chrome-version-3101776/

**Comment by jonesmac** [comment]
nm @Sc2KiiiA.  I figured it out!  Your screen share was super helpful as once I slowed it down I could see that it did successfully resolve the profile, but failed to load the preview of the result that caused the crash.  Pushing a fix here shortly.

**Comment by Sc2KiiiA** [comment]
(xyOS) V2.3 3

![Screenshot_20240814_164107_Chrome.png](https://github.com/user-attachments/assets/e7caedc1-6ce5-4fec-b870-dfa7854fdfa4)

(Google) 127.0.6533.103

![Screenshot_20240814_164226_Google Play Store.png](https://github.com/user-attachments/assets/82950dc8-1bd7-4090-b71a-55aafa056099)
