### ISSUE TITLE
cant type xNS Fields

### ISSUE THREAD

**Issue by Sc2KiiiA** [XYOracleNetwork/os#32]
**Describe the bug**
when viewing xNS `https://node.xyo.network/name-service` `https://node.xyo.network/name-service/my-names` ect... all four boxes'

**To Reproduce**
1. visit https://node.xyo.network/name-service/my-names
2. Click on 'the box to type'
3. Nothing happends

**Expected behavior**
would think I should be able to type.

**Screenshots**

https://github.com/user-attachments/assets/5f882ae4-93b9-4c54-ab27-3911a3e7539c

**Desktop (please complete the following information):**
 - OS: WIndows 10
 - Browser Chrome
 - Version 127.0.6533.122 (Official Build) (64-bit)

**Comment by jonesmac** [comment]
Thanks @Sc2KiiiA.  I wasn't able to reproduce your issue exactly on mac or windows.  I do see there's an error there that looks like a submission was made with an invalid length.  It looks like you can hit enter and search when there is not input even though the button is disabled.  I fixed that behavior in the next release.

Can you confirm that it doesn't the keyboard prevention behavior on another browser?

**Comment by Sc2KiiiA** [comment]
It works on android. But when trying to type into any of the tabs fields I get no response. I'm not the only user seeing this ![Screenshot_20240828_155622_Discord.png](https://github.com/user-attachments/assets/ef028d5f-58c5-43a4-8cce-f0bb31f0c521)

**Comment by LewSales** [comment]
A different Video of side by side Chrome / Brave (left/Right)
Chrome just doesn't allow me to type. Spec's Above 

[Video](https://cdn.discordapp.com/attachments/1000089856694816788/1278527808137597012/2024-08-28_19-31-22.mp4?ex=66d1214f&is=66cfcfcf&hm=16036053903667b68283fe48bf8d2b80adb19cb9ea02d8bb5735fe2dc3339e03&)

**Comment by arietrouw** [comment]
@LewSales Thanks for sending the video.  Is the device you are using a Surface Tablet?

**Comment by arietrouw** [comment]
@LewSales Also, can you tell me the version of the xyOS from the About dApp?

**Comment by arietrouw** [comment]
@Sc2KiiiA What hardware (surface tablet?) and version of xyOS are you using in your video?

**Comment by LewSales** [comment]
Current xyOS Version: v2.3.3

![Screenshot (80)](https://github.com/user-attachments/assets/944e3aba-a70f-45ca-91cb-91743f08af59)

Desktop;
its a Custom build, I Built it back in 2o2o;
I could Specify CPU,Ram,Motherboard,GFX and other fine detals if needed;

Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz   3.40 GHz
 
Windows 10; 
Edition; Windows 10 Pro
Version; 22H2
OS Build; 19045.4780
Experience; Windows Feature Experience Pack 1000.19060.1000.0


chrome; Version 128.0.6613.85 (Official Build) (64-bit)
