### ISSUE TITLE
Icon overlap with footer on Main xyOS.

### ISSUE THREAD

**Issue by jebscc** [XYOracleNetwork/os#34]
**Describe the bug**
When you click the ... on the footer, it does expand as expected but the bottom two app icons overlap the expansion of the footer. 

**To Reproduce**
1. Navigate to https://node.xyo.network/
2. Click on ... on the footer
3. View the bug with two icons overlapping the expansion of the footer.

**Expected behavior**
When footer expands, it should be most top object that will overlap everything in it's path. By allowing the footer to overlap other objects (like the icons) then the issue wouldn't occur as the icons would be below the footer object. Allowing you to view everything being displayed in the expansion of the footer when the ... button is click on.

**Screenshots**
![image](https://github.com/user-attachments/assets/b148ecd6-ee23-43b4-bae1-d560f036b9c6)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 127.0.6533.120

**Comment by jonesmac** [comment]
Thanks @jebscc fixed in the next release
