### ISSUE TITLE
EXODUS WALLET does not support contract 0x55296f69f40ea6d20e478533c15a6b08b654e758

### ISSUE THREAD

**Issue by nyinet** [XYOracleNetwork/os#38]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

Thank you so much.
If possible please add wallet compatability Exodus wallet app mobile

**Comment by jonesmac** [comment]
@nyinet not sure if this is the right repository for your issue.  This repo is for XYOS issues and EXODUS WALLET.
