### ISSUE TITLE
Profile Discover Button not clickable

### ISSUE THREAD

**Issue by jebscc** [XYOracleNetwork/os#8]
**Describe the bug**
This bug occurs only when you close the window while on the discover button. When you return back to "Profile" dApp you are landed on the "Home" tab, but when you click on "Discover" nothing occurs. It's not until you click on Home or Friends before Discover will work.

**To Reproduce**
1. Launch Profile dApp.
2. Click on "Discover".
3. Click "X" to close Profile dApp.
4. Launch Profile dApp again.
5. Click Discover. This is where the bug occurs as no action will be taken when you click on discover.

**Expected behavior**
It is expected to be able to click on "Discover" at any given time when the Profile dApp is viewable and action will be taken to allow you to navigate to the Discover profiles feature. You shouldn't need to click on home or friends to enable navigation on the Discover mouse click action.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.91

**Comment by jebscc** [comment]
I've taken a deeper look into this and this appears to have a common issue between multiple dApp's which seems to be always be related to the last tab you was on. For example; launch the Name Service dApp and select another tab other than "Buy Names". Close the dApp and reopen. Go back to the exact tab you was on and notice what happens which you should see that no matter what you do. You can't navigate back to the last tab until you select a different tab. Once you have done this, you can go back and click on the last tab you had open when you closed the dApp. So far this behavior occurs on the following dApps:
   
   1. Name Service
   2. Profile
   3. Settings

Here are a few examples:

Example 1:
   1. Launch Name Service dApp.
   2. Click "My Names"
   3. Click "X" to exit dApp.
   4. Relaunch Name Service dApp.
   5. Click "My Names" again and see that it doesn't complete the action to go to that page.

Example 2:
   1. Launch Name Service dApp.
   2. Click "Randomizer"
   3. Click "X" to exit dApp.
   4. Relaunch Name Service dApp.
   5. Click "Randomizer" again and see that it doesn't complete the action to go to that page.

Example 3:
   1. Launch Name Service dApp.
   2. Click "Check Out"
   3. Click "X" to exit dApp.
   4. Relaunch Name Service dApp.
   5. Click "Check Out" again and see that it doesn't complete the action to go to that page.

 Example 4:
   1. Launch Settings dApp.
   2. Click "Appearance"
   3. Click "X" to exit dApp.
   4. Relaunch Settings  dApp.
   5. Click "Appearance" again and see that it doesn't complete the action to go to that page.

Temporary Solution to Fix the issue: Click on a different tab within the dApp and then go back to click on the button that is affected by this issue.

Note: This doesn't seem to be affecting dApps in between. For Example, if I click on the second button in Settings "Appearance" and second button in Profile "Discover" then each will navigate to the page assigned to that tab. This issue seems to be affecting each dApp separately.

**Comment by jonesmac** [comment]
@jebscc thank you so much for the detailed explanation.  I know I saw it happen before but had not figured out how to reproduce it consistently.  I think I've got a fix for it that will come in the next release.

**Comment by jebscc** [comment]
You’re welcome, @jonesmac! 😃
