### ISSUE TITLE
Viewing "view profile"

### ISSUE THREAD

**Issue by Ashcoinum** [XYOracleNetwork/os#9]
**Describe the bug**
I went to click "View Profile" of lewsales.xyo and the bar that pops up with his information is squeezed, not displaying all information

**To Reproduce**
1. Go to 'Profile Dapp'
2. Click on 'Search Profiles", Search lewsales.xyo, view profile

3
![Screenshot 2024-05-01 222708 profile view](https://github.com/XYOracleNetwork/os/assets/168700567/0b716518-2d8c-4656-944a-20477a82949d)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser [e.g. ]

**Smartphone (please complete the following information):**
 - Device: [e.g. desktop]
 - OS: [e.g. windows 11]
 - Browser [e.g. edge]
 - Version [e.g.  124.0.2478.67]

**Additional context**

**Comment by arietrouw** [comment]
Confirmed
